kind: pipeline
type: docker
name: build-deb

steps:
  - name: package
    image: myoung34/github-runner:ubuntu-noble
    commands:
      - chmod +x build.sh
      - ./build.sh

trigger:
  branch:
    - main
